# Classification Problem Lab
## Predict Stay/Leave The Company

Your boss was extremely happy with your work and decided to entrust you with a task. They've seen a lot of people leave the company recently and they would like to understand why that's happening. They have collected historical data on employees and they would like you to build a model that is able to predict which employee will leave next. The would like a model that is better than random guessing. They also prefer false negatives than false positives, in this first phase. Fields in the dataset include:

- Employee satisfaction level
- Last evaluation
- Number of projects
- Average monthly hours
- Time spent at the company
- Whether they have had a work accident
- Whether they have had a promotion in the last 5 years
- Department
- Salary
- Whether the employee has left (เป็นตัวแปรที่ต้องการทำนาย)

Your goal is to predict the binary outcome variable `left` using the rest of the data. Since the outcome is binary, this is a classification problem.

This dataset comes from https://www.kaggle.com/ludobenistant/hr-analytics/ and is released under [CC BY-SA 4.0 License](https://creativecommons.org/licenses/by-sa/4.0/).

#### Step 1 — Data Pre-processing (อ่าน data เข้ามา มีากรดูสถิติเกี่ยวกับ data เบื้องต้น มีการจัดการ column ที่เป็นข้อความให้เป็นตัวเลขหรือรูปแบบที่สามารถนำไปใช้ได้)

In [ ]:
#import ...
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

df = pd.read_csv('https://raw.githubusercontent.com/TipGreenTea/MUICT-AST-IntroToAI_Datasets/main/HR_comma_sep.csv')
df

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years,sales,salary,left
0,0.38,0.53,2,157,3,0,0,sales,low,1
1,0.80,0.86,5,262,6,0,0,sales,medium,1
2,0.11,0.88,7,272,4,0,0,sales,medium,1
3,0.72,0.87,5,223,5,0,0,sales,low,1
4,0.37,0.52,2,159,3,0,0,sales,low,1
...,...,...,...,...,...,...,...,...,...,...
14994,0.40,0.57,2,151,3,0,0,support,low,1
14995,0.37,0.48,2,160,3,0,0,support,low,1
14996,0.37,0.53,2,143,3,0,0,support,low,1
14997,0.11,0.96,6,280,4,0,0,support,low,1
14998,0.37,0.52,2,158,3,0,0,support,low,1

In [3]:
df.head(10)

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years,sales,salary,left
0,0.38,0.53,2,157,3,0,0,sales,low,1
1,0.80,0.86,5,262,6,0,0,sales,medium,1
2,0.11,0.88,7,272,4,0,0,sales,medium,1
3,0.72,0.87,5,223,5,0,0,sales,low,1
4,0.37,0.52,2,159,3,0,0,sales,low,1
5,0.41,0.50,2,153,3,0,0,sales,low,1
6,0.10,0.77,6,247,4,0,0,sales,low,1
7,0.92,0.85,5,259,5,0,0,sales,low,1
8,0.89,1.00,5,224,5,0,0,sales,low,1
9,0.42,0.53,2,142,3,0,0,sales,low,1

In [5]:
df['Work_accident'].value_counts()

Work_accident
0    12830
1     2169
Name: count, dtype: int64

In [7]:
X = df.iloc[:, 1:-1].values
Y = df.iloc[:, -1].values

In [8]:
X

array([[0.53, 2, 157, ..., 0, 'sales', 'low'],
       [0.86, 5, 262, ..., 0, 'sales', 'medium'],
       [0.88, 7, 272, ..., 0, 'sales', 'medium'],
       ...,
       [0.53, 2, 143, ..., 0, 'support', 'low'],
       [0.96, 6, 280, ..., 0, 'support', 'low'],
       [0.52, 2, 158, ..., 0, 'support', 'low']], dtype=object)

In [9]:
Y

array([1, 1, 1, ..., 1, 1, 1])

In [16]:
#CODE HERE
#สามารถตัด column sales, salary ออกจาก X ได้เลย
X = df.drop(['sales', 'salary'], axis=1)
X.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years,left
0,0.38,0.53,2,157,3,0,0,1
1,0.80,0.86,5,262,6,0,0,1
2,0.11,0.88,7,272,4,0,0,1
3,0.72,0.87,5,223,5,0,0,1
4,0.37,0.52,2,159,3,0,0,1

#### Step 2 — Separating Your Training and Testing Datasets

In [17]:
#CODE HERE
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [18]:
X_train

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years,left
12766,0.75,0.81,5,227,5,0,0,1
3536,0.13,0.91,2,149,5,0,0,0
10295,0.67,0.74,3,226,3,0,0,0
2137,0.52,0.43,2,199,2,0,0,0
14774,0.10,0.77,7,291,4,0,0,1
...,...,...,...,...,...,...,...,...
13123,0.52,0.57,3,270,3,0,0,0
3264,0.59,0.79,4,209,2,0,0,0
9845,0.69,0.94,5,259,2,0,0,0
10799,0.78,0.59,5,236,3,0,0,0
2732,0.56,0.68,5,203,2,0,0,0

In [19]:
X_test

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years,left
1670,0.44,0.57,2,141,3,0,0,1
13378,0.55,0.96,3,194,3,0,0,0
10233,0.72,0.67,5,210,2,0,0,0
4719,0.96,0.75,4,177,2,0,0,0
7003,0.96,0.54,3,198,3,0,0,0
...,...,...,...,...,...,...,...,...
14035,0.75,0.79,4,263,3,0,1,0
8469,0.92,0.49,5,178,2,1,0,0
12453,0.37,0.54,2,145,3,0,0,1
9431,0.52,0.61,4,163,2,0,0,0
4202,0.13,0.65,4,194,4,0,0,0

In [20]:
Y_train

array([1, 0, 0, ..., 0, 0, 0])

In [21]:
Y_test

array([1, 0, 0, ..., 1, 0, 0])

#### Step 3 — Transforming the Data (Optional จะทำ Feature Scaling หรือไม่ก็ได้ ถ้าไม่ทำ สามารถข้าม step นี้ไปได้เลย)

In [22]:
#CODE HERE
from sklearn.preprocessing import StandardScaler, MinMaxScaler
#sc = StandardScaler()
sc = MinMaxScaler()
X_train = sc.fit_transform(X_train) #สร้างหน่วยที่จะแปลงแค่ dataset ชุดนี้
X_train

array([[0.72527473, 0.703125  , 0.6       , ..., 0.        , 0.        ,
        1.        ],
       [0.04395604, 0.859375  , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.63736264, 0.59375   , 0.2       , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.65934066, 0.90625   , 0.6       , ..., 0.        , 0.        ,
        0.        ],
       [0.75824176, 0.359375  , 0.6       , ..., 0.        , 0.        ,
        0.        ],
       [0.51648352, 0.5       , 0.6       , ..., 0.        , 0.        ,
        0.        ]])

#### Step 4 — Building ML models (สร้าง model และ train model จาก training data)

In [23]:
#CODE HERE
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
model = LogisticRegression(random_state = 0)
#model = SVC()

In [24]:
model.fit(X_train, Y_train)

LogisticRegression(random_state=0)

#### Step 5 — Running Predictions on the Test Set (อธิบายว่าได้ accuracy, precision, recall เท่าไรให้กับ LA)

In [25]:
#CODE HERE
y_pred = model.predict(sc.transform(X_test))

In [32]:
from sklearn.metrics import classification_report
report = classification_report(Y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2299
           1       1.00      1.00      1.00       701

    accuracy                           1.00      3000
   macro avg       1.00      1.00      1.00      3000
weighted avg       1.00      1.00      1.00      3000

In [26]:
y_pred

array([1, 0, 0, ..., 1, 0, 0])

In [29]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, y_pred)

array([[2299,    0],
       [   0,  701]])

**Accurracy**

In [30]:
(84+45)/(84+45+5+3)

0.9416058394160584

In [31]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, y_pred)

1.0